/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accdat.papergames.Vista;

import accdat.papergames.Controlador.Controlador;
import accdat.papergames.Modelo.Persistencia.ModoJuego;
import accdat.papergames.Modelo.Persistencia.Plataforma;
import accdat.papergames.Modelo.Persistencia.Videojuego;
import static accdat.papergames.Vista.InterfazVista.OPERACION_MODIFICAR_VIDEOJUGO;
import java.awt.Checkbox;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.JScrollPane;

/**
 *
 * @author rezzt
 */
public class VentanaModVideojuego extends javax.swing.JFrame implements InterfazVista {
  private Controlador controlador;
  private Videojuego baseVideojuego;
  
  private String titulo;
  private String generoSelected;
  private String descripcionSelected;
  private int anioSalida;
  private List<Checkbox> listaPlataformasSelected = new ArrayList<>();
  private int pegiSelected;
  private List<Checkbox> listaModosJuegoSelected = new ArrayList<>();
  
  private List<Plataforma> listaPlataformasVideojuego = new ArrayList<>();
  private List<ModoJuego> listaModosJuegoVideojuego = new ArrayList<>();
  
  /**
   * Creates new form VentanaModVideojuego
   */
  public VentanaModVideojuego() {
    initComponents();
    iniciarComponentes();
  }
  
  private void iniciarComponentes () {
    panelListaPlataformas.setLayout(new java.awt.GridLayout(0,1));
    panelListaModosJuego.setLayout(new java.awt.GridLayout(0,1));
    btnAceptar.setActionCommand(OPERACION_MODIFICAR_VIDEOJUGO);
    
    cargarOpcionesGenero();
    cargarOpcionesModosJuego();
    cargarOpcionesPlataforma();
    cargarOpcionesPEGI();
    cargarCamposDatosVideojuego();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    lblTituloVentana = new javax.swing.JLabel();
    panelProp1 = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    txtTitulo = new javax.swing.JTextField();
    lblAnioSalida = new javax.swing.JLabel();
    spinnerAnioSalida = new javax.swing.JSpinner();
    lblPEGI = new javax.swing.JLabel();
    cboxListaPegi = new javax.swing.JComboBox<>();
    lblGenero = new javax.swing.JLabel();
    cboxListaGeneros = new javax.swing.JComboBox<>();
    panelProp2 = new javax.swing.JPanel();
    lblPlataformas = new javax.swing.JLabel();
    panelListaPlataformas = new javax.swing.JPanel();
    panelProp3 = new javax.swing.JPanel();
    lblTxtDescrip = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtDescripcion = new javax.swing.JTextArea();
    panelProp4 = new javax.swing.JPanel();
    lblModosJuego = new javax.swing.JLabel();
    panelListaModosJuego = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    btnAceptar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(0, 0));
    setSize(new java.awt.Dimension(0, 0));

    jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

    lblTituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTituloVentana.setText("MODIFICACION | VIDEOJUEGO");
    lblTituloVentana.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    panelProp1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

    lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTitulo.setText("Titulo:");

    lblAnioSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblAnioSalida.setText("Año Salida:");

    spinnerAnioSalida.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)2020), Short.valueOf((short)2000), Short.valueOf((short)9000), Short.valueOf((short)1)));

    lblPEGI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblPEGI.setText("PEGI:");

    lblGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblGenero.setText("Genero:");

    javax.swing.GroupLayout panelProp1Layout = new javax.swing.GroupLayout(panelProp1);
    panelProp1.setLayout(panelProp1Layout);
    panelProp1Layout.setHorizontalGroup(
      panelProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtTitulo)
          .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lblAnioSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(spinnerAnioSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
          .addComponent(lblPEGI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cboxListaPegi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cboxListaGeneros, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    panelProp1Layout.setVerticalGroup(
      panelProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(spinnerAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblPEGI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cboxListaPegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cboxListaGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    panelProp2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
    panelProp2.setMinimumSize(new java.awt.Dimension(100, 203));
    panelProp2.setPreferredSize(new java.awt.Dimension(100, 203));

    lblPlataformas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblPlataformas.setText("Plataformas:");

    javax.swing.GroupLayout panelListaPlataformasLayout = new javax.swing.GroupLayout(panelListaPlataformas);
    panelListaPlataformas.setLayout(panelListaPlataformasLayout);
    panelListaPlataformasLayout.setHorizontalGroup(
      panelListaPlataformasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelListaPlataformasLayout.setVerticalGroup(
      panelListaPlataformasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout panelProp2Layout = new javax.swing.GroupLayout(panelProp2);
    panelProp2.setLayout(panelProp2Layout);
    panelProp2Layout.setHorizontalGroup(
      panelProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp2Layout.createSequentialGroup()
        .addGroup(panelProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblPlataformas, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
          .addGroup(panelProp2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(panelListaPlataformas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    panelProp2Layout.setVerticalGroup(
      panelProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblPlataformas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelListaPlataformas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    panelProp3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

    lblTxtDescrip.setText("Descripion:");

    txtDescripcion.setColumns(20);
    txtDescripcion.setRows(5);
    jScrollPane1.setViewportView(txtDescripcion);

    javax.swing.GroupLayout panelProp3Layout = new javax.swing.GroupLayout(panelProp3);
    panelProp3.setLayout(panelProp3Layout);
    panelProp3Layout.setHorizontalGroup(
      panelProp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelProp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblTxtDescrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
        .addContainerGap())
    );
    panelProp3Layout.setVerticalGroup(
      panelProp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTxtDescrip)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1)
        .addContainerGap())
    );

    panelProp4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
    panelProp4.setMinimumSize(new java.awt.Dimension(100, 203));

    lblModosJuego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblModosJuego.setText("Modos de Juego:");

    javax.swing.GroupLayout panelListaModosJuegoLayout = new javax.swing.GroupLayout(panelListaModosJuego);
    panelListaModosJuego.setLayout(panelListaModosJuegoLayout);
    panelListaModosJuegoLayout.setHorizontalGroup(
      panelListaModosJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelListaModosJuegoLayout.setVerticalGroup(
      panelListaModosJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout panelProp4Layout = new javax.swing.GroupLayout(panelProp4);
    panelProp4.setLayout(panelProp4Layout);
    panelProp4Layout.setHorizontalGroup(
      panelProp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProp4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelProp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(panelListaModosJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lblModosJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        .addContainerGap())
    );
    panelProp4Layout.setVerticalGroup(
      panelProp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblModosJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelListaModosJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblTituloVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(panelProp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelProp2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelProp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelProp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTituloVentana)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelProp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelProp2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
          .addComponent(panelProp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelProp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

    btnAceptar.setText("Aceptar");
    btnAceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAceptarActionPerformed(evt);
      }
    });

    btnCancelar.setText("Cancelar");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnCancelar))
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnCancelarActionPerformed

  private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    recogerDatosCampos();
  }//GEN-LAST:event_btnAceptarActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAceptar;
  private javax.swing.JButton btnCancelar;
  private javax.swing.JComboBox<String> cboxListaGeneros;
  private javax.swing.JComboBox<String> cboxListaPegi;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblAnioSalida;
  private javax.swing.JLabel lblGenero;
  private javax.swing.JLabel lblModosJuego;
  private javax.swing.JLabel lblPEGI;
  private javax.swing.JLabel lblPlataformas;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JLabel lblTituloVentana;
  private javax.swing.JLabel lblTxtDescrip;
  private javax.swing.JPanel panelListaModosJuego;
  private javax.swing.JPanel panelListaPlataformas;
  private javax.swing.JPanel panelProp1;
  private javax.swing.JPanel panelProp2;
  private javax.swing.JPanel panelProp3;
  private javax.swing.JPanel panelProp4;
  private javax.swing.JSpinner spinnerAnioSalida;
  private javax.swing.JTextArea txtDescripcion;
  private javax.swing.JTextField txtTitulo;
  // End of variables declaration//GEN-END:variables
 //------------------------------------------------------------------------------------------------------------->
  private void cargarCamposDatosVideojuego () {
    this.titulo = this.baseVideojuego.getTitulo();
    this.generoSelected = this.baseVideojuego.getNombreGenero().getNombreGenero();
    this.pegiSelected = this.baseVideojuego.getPegi();
    this.descripcionSelected = this.baseVideojuego.getDescripcion();
    this.anioSalida = this.baseVideojuego.getAño();
    List<Plataforma> listaPlataformas = (List<Plataforma>) this.baseVideojuego.getPlataformaCollection();
    List<ModoJuego> listaModosJuego = (List<ModoJuego>) this.baseVideojuego.getModoJuegoCollection();
    
    cargarPlataformaVideojuego(listaPlataformas);
    cargarModosJuegoVideojuego(listaModosJuego);
    
    txtTitulo.setText(this.titulo);
    txtDescripcion.setText(this.descripcionSelected);
    marcarOpcionGenero(this.generoSelected);
    marcarOpcionPEGI(this.pegiSelected);
  }
  
  private void recogerDatosCampos () {
    this.baseVideojuego.setTitulo(txtTitulo.getText());
    this.baseVideojuego.setDescripcion(txtDescripcion.getText());
    this.baseVideojuego.setAño((short) this.anioSalida);
    this.baseVideojuego.setNombreGenero(this.controlador.encontrarGenero((String) this.cboxListaGeneros.getSelectedItem()));
    
    insertarModosJuegoVideojuego();
    insertarPlataformasVideojuego();
    this.baseVideojuego.setModoJuegoCollection(listaModosJuegoVideojuego);
    this.baseVideojuego.setPlataformaCollection(listaPlataformasVideojuego);
  }
  
 //------------------------------------------------------------------------------------------------------------->
  private void cargarOpcionesGenero () {
    cboxListaGeneros.removeAll();
    List<String> listaGeneros = controlador.cargarNombresGeneros();
    
    for (String aux : listaGeneros) {
      cboxListaGeneros.addItem(aux);
    }
  }
  private void marcarOpcionGenero (String inputNombreGenero) {
    for (int i=0; i < cboxListaGeneros.getItemCount(); i++) {
      if (cboxListaGeneros.getItemAt(i).equals(inputNombreGenero)) {
        cboxListaGeneros.setSelectedIndex(i);
      }
    }
  }
  
  private void cargarOpcionesPlataforma () {
    panelListaPlataformas.removeAll();
    List<String> listaPlataformas = controlador.cargarNombresPlataformas();
    
    for (String aux : listaPlataformas) {
      java.awt.Checkbox genCheckBox = new Checkbox(aux, false);
      listaPlataformasSelected.add(genCheckBox);
      panelListaPlataformas.add(genCheckBox);
    }
  }
  private void cargarPlataformaVideojuego (List<Plataforma> inputListaPlataforma) {    
    for (Checkbox aux : listaPlataformasSelected) {
      for (Plataforma aux2 : inputListaPlataforma) {
        if (aux.getLabel().equals(aux2.getNombrePlataforma())) {
          aux.setState(true);
        }
      }
    }
  }
  private void insertarPlataformasVideojuego () {
    for (Checkbox aux : listaPlataformasSelected) {
      if (aux.getState() == true) {
        listaPlataformasVideojuego.add(this.controlador.encontrarPlataforma(aux.getLabel()));
      }
    }
  }
  
  private void cargarOpcionesModosJuego () {
    panelListaModosJuego.removeAll();
    List<String> listaModosJuego = controlador.cargarNombresModoJuego();
    
    for (String aux : listaModosJuego) {
      java.awt.Checkbox genCheckBox = new Checkbox(aux, false);
      listaModosJuegoSelected.add(genCheckBox);
      panelListaModosJuego.add(genCheckBox);
    }
  }
  private void cargarModosJuegoVideojuego (List<ModoJuego> inputListaPlataforma) { 
    for (Checkbox aux : listaPlataformasSelected) {
      for (ModoJuego aux2 : inputListaPlataforma) {
        if (aux.getLabel().equals(aux2.getNombreModoJuego())) {
          aux.setState(true);
        }
      }
    }
  }
  private void insertarModosJuegoVideojuego () {
    for (Checkbox aux : listaModosJuegoSelected) {
      if (aux.getState() == true) {
        listaModosJuegoVideojuego.add(this.controlador.encontrarModoJuego(aux.getLabel()));
      }
    }
  }
  
  private void cargarOpcionesPEGI () {
    cboxListaPegi.removeAll();
    List<String> listaPEGI = new ArrayList<>();
    
    for (Integer aux : controlador.cargarPEGIs()) {
      listaPEGI.add(Integer.toString(aux));
    }
    
    for (String aux : listaPEGI) {
      cboxListaPegi.addItem(aux);
    }
  }
    private void marcarOpcionPEGI (int inputPEGI) {
    for (int i=0; i < cboxListaPegi.getItemCount(); i++) {
      if (Integer.parseInt(cboxListaGeneros.getItemAt(i)) == inputPEGI) {
        cboxListaGeneros.setSelectedIndex(i);
      }
    }
  }
  
 //------------------------------------------------------------------------------------------------------------->
  public Videojuego getBaseVideojuego() {
    return baseVideojuego;
  }

  public void setBaseVideojuego(Videojuego baseVideojuego) {
    this.baseVideojuego = baseVideojuego;
  }

  @Override
  public void agregarVisores(List<Videojuego> inputListaVideojuegos) {
    //no hace nada
  }

  @Override
  public void setControlador(Controlador c) {
    this.controlador = c;
    btnAceptar.addActionListener(c);
  }

  @Override
  public void arranca() {
    pack();
    setLocationRelativeTo(null);
    setVisible(true);
  }

  @Override
  public void haceAlgo(String s) {
    // no hace nada
  }
}
