/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accdat.papergames.Vista;

import accdat.papergames.Controlador.Controlador;
import accdat.papergames.Modelo.Persistencia.ModoJuego;
import accdat.papergames.Modelo.Persistencia.Videojuego;
import java.awt.BorderLayout;
import java.awt.Checkbox;
import java.awt.CheckboxGroup;
import java.awt.SystemColor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;


/**
 *
 * @author rezzt
 */
public class VentanaPrincipal extends javax.swing.JFrame implements InterfazVista {
  private Controlador controlador;
  private List<Checkbox> listaGenerosSelected = new ArrayList<>();
  private List<Checkbox> listaPlataformasSelected = new ArrayList<>();
  private List<Checkbox> listaPEGISelected = new ArrayList<>();
  private List<Checkbox> listaModosJuegoSelected = new ArrayList<>();
  
  
  
  /**
   * Creates new form VentanaPrincipal
   */
  public VentanaPrincipal() {
    initComponents();
    panelOpcionesGenero.setLayout(new java.awt.GridLayout(0,1));
    panelOpcionesPlataforma.setLayout(new java.awt.GridLayout(0,1));
    panelOpcionesModoJuego.setLayout(new java.awt.GridLayout(0,1));
    panelOpcionesPEGI.setLayout(new java.awt.GridLayout(0,1));
    
    jVisorVideojuego.setLayout(new java.awt.GridLayout(0, 1));
    JScrollPane scrollPaneListaVideojuegos = new JScrollPane(jVisorVideojuego);
    scrollPaneListaVideojuegos.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    scrollPaneListaVideojuegos.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    
//    cargarOpcionesGenero();
//    cargarOpcionesModosJuego();
//    cargarOpcionesPlataforma();
//    cargarOpcionesPEGI();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelFiltros = new javax.swing.JPanel();
    txtGenero = new javax.swing.JLabel();
    txtPlataforma = new javax.swing.JLabel();
    txtAnioPublicacion = new javax.swing.JLabel();
    txtPegi = new javax.swing.JLabel();
    txtModoJuego = new javax.swing.JLabel();
    panelOpcionesGenero = new javax.swing.JPanel();
    panelOpcionesPlataforma = new javax.swing.JPanel();
    panelOpcionesModoJuego = new javax.swing.JPanel();
    panelOpcionesPEGI = new javax.swing.JPanel();
    spinnerAnioSalida = new javax.swing.JSpinner();
    btnModificar = new javax.swing.JButton();
    btnAgregarJuego = new javax.swing.JButton();
    btnEliminar = new javax.swing.JButton();
    btnBuscar = new javax.swing.JButton();
    jVisorVideojuego = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(1200, 800));

    panelFiltros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
    panelFiltros.setPreferredSize(new java.awt.Dimension(190, 632));

    txtGenero.setText("Género");

    txtPlataforma.setText("Plataforma");

    txtAnioPublicacion.setText("Año de publicación");

    txtPegi.setText("PEGI");

    txtModoJuego.setText("Modo de juego");
    txtModoJuego.setMaximumSize(new java.awt.Dimension(85, 17));
    txtModoJuego.setMinimumSize(new java.awt.Dimension(85, 17));
    txtModoJuego.setPreferredSize(new java.awt.Dimension(85, 17));

    javax.swing.GroupLayout panelOpcionesGeneroLayout = new javax.swing.GroupLayout(panelOpcionesGenero);
    panelOpcionesGenero.setLayout(panelOpcionesGeneroLayout);
    panelOpcionesGeneroLayout.setHorizontalGroup(
      panelOpcionesGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelOpcionesGeneroLayout.setVerticalGroup(
      panelOpcionesGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 112, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout panelOpcionesPlataformaLayout = new javax.swing.GroupLayout(panelOpcionesPlataforma);
    panelOpcionesPlataforma.setLayout(panelOpcionesPlataformaLayout);
    panelOpcionesPlataformaLayout.setHorizontalGroup(
      panelOpcionesPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelOpcionesPlataformaLayout.setVerticalGroup(
      panelOpcionesPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 124, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout panelOpcionesModoJuegoLayout = new javax.swing.GroupLayout(panelOpcionesModoJuego);
    panelOpcionesModoJuego.setLayout(panelOpcionesModoJuegoLayout);
    panelOpcionesModoJuegoLayout.setHorizontalGroup(
      panelOpcionesModoJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelOpcionesModoJuegoLayout.setVerticalGroup(
      panelOpcionesModoJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 112, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout panelOpcionesPEGILayout = new javax.swing.GroupLayout(panelOpcionesPEGI);
    panelOpcionesPEGI.setLayout(panelOpcionesPEGILayout);
    panelOpcionesPEGILayout.setHorizontalGroup(
      panelOpcionesPEGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelOpcionesPEGILayout.setVerticalGroup(
      panelOpcionesPEGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    spinnerAnioSalida.setModel(new javax.swing.SpinnerNumberModel(2020, 2000, 2029, 1));

    javax.swing.GroupLayout panelFiltrosLayout = new javax.swing.GroupLayout(panelFiltros);
    panelFiltros.setLayout(panelFiltrosLayout);
    panelFiltrosLayout.setHorizontalGroup(
      panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelFiltrosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtPegi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtModoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtPlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelOpcionesGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelOpcionesPlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelOpcionesModoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelOpcionesPEGI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtAnioPublicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
          .addComponent(spinnerAnioSalida))
        .addContainerGap())
    );
    panelFiltrosLayout.setVerticalGroup(
      panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelFiltrosLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(txtGenero)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelOpcionesGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtPlataforma)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelOpcionesPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtModoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelOpcionesModoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtPegi)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(panelOpcionesPEGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtAnioPublicacion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(spinnerAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnModificar.setText("Modificar");
    btnModificar.setEnabled(false);
    btnModificar.setMaximumSize(new java.awt.Dimension(75, 30));
    btnModificar.setMinimumSize(new java.awt.Dimension(75, 30));
    btnModificar.setPreferredSize(new java.awt.Dimension(75, 30));
    btnModificar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnModificarActionPerformed(evt);
      }
    });

    btnAgregarJuego.setText("Agregar Videojuego");
    btnAgregarJuego.setMaximumSize(new java.awt.Dimension(75, 30));
    btnAgregarJuego.setMinimumSize(new java.awt.Dimension(75, 30));
    btnAgregarJuego.setPreferredSize(new java.awt.Dimension(75, 30));

    btnEliminar.setText("Eliminar");
    btnEliminar.setEnabled(false);
    btnEliminar.setMaximumSize(new java.awt.Dimension(75, 30));
    btnEliminar.setMinimumSize(new java.awt.Dimension(75, 30));
    btnEliminar.setPreferredSize(new java.awt.Dimension(75, 30));

    btnBuscar.setText("Buscar");
    btnBuscar.setMaximumSize(new java.awt.Dimension(75, 30));
    btnBuscar.setMinimumSize(new java.awt.Dimension(75, 30));
    btnBuscar.setPreferredSize(new java.awt.Dimension(75, 30));

    javax.swing.GroupLayout jVisorVideojuegoLayout = new javax.swing.GroupLayout(jVisorVideojuego);
    jVisorVideojuego.setLayout(jVisorVideojuegoLayout);
    jVisorVideojuegoLayout.setHorizontalGroup(
      jVisorVideojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 708, Short.MAX_VALUE)
    );
    jVisorVideojuegoLayout.setVerticalGroup(
      jVisorVideojuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
          .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnAgregarJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jVisorVideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnAgregarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jVisorVideojuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void iniciarComponentes () {
    panelOpcionesGenero.setLayout(new java.awt.GridLayout(0,1));
    panelOpcionesPlataforma.setLayout(new java.awt.GridLayout(0,1));
    panelOpcionesModoJuego.setLayout(new java.awt.GridLayout(0,1));
    panelOpcionesPEGI.setLayout(new java.awt.GridLayout(0,1));
    
    jVisorVideojuego.setLayout(new java.awt.GridLayout(0, 1));
    JScrollPane scrollPaneListaVideojuegos = new JScrollPane(jVisorVideojuego);
    scrollPaneListaVideojuegos.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    scrollPaneListaVideojuegos.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

//    cargarOpcionesGenero();
//    cargarOpcionesModosJuego();
//    cargarOpcionesPlataforma();
//    cargarOpcionesPEGI();
//    controlador.rellenarDatos(this);
  }
  
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.setVisible(false);
        VentanaModVideojuego ventana = new VentanaModVideojuego();
        ventana.setControlador(this.controlador);
        ventana.arranca();
    }//GEN-LAST:event_btnModificarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAgregarJuego;
  private javax.swing.JButton btnBuscar;
  private javax.swing.JButton btnEliminar;
  private javax.swing.JButton btnModificar;
  private javax.swing.JPanel jVisorVideojuego;
  private javax.swing.JPanel panelFiltros;
  private javax.swing.JPanel panelOpcionesGenero;
  private javax.swing.JPanel panelOpcionesModoJuego;
  private javax.swing.JPanel panelOpcionesPEGI;
  private javax.swing.JPanel panelOpcionesPlataforma;
  private javax.swing.JSpinner spinnerAnioSalida;
  private javax.swing.JLabel txtAnioPublicacion;
  private javax.swing.JLabel txtGenero;
  private javax.swing.JLabel txtModoJuego;
  private javax.swing.JLabel txtPegi;
  private javax.swing.JLabel txtPlataforma;
  // End of variables declaration//GEN-END:variables
  
 
  
 //-------------------------------------------------------------------------------------------------------------->
  
  
 //-------------------------------------------------------------------------------------------------------------->
  
  
 //-------------------------------------------------------------------------------------------------------------->

  @Override
  public void agregarVisores(List<Videojuego> inputListaVideojuegos) {
    jVisorVideojuego.removeAll();
    for (Videojuego aux : inputListaVideojuegos) {
      VisorVideojuegos visor = new VisorVideojuegos();
      JPanel contenedorVisor = new JPanel(new BorderLayout());
      contenedorVisor.setBorder(new EmptyBorder(5, 10, 5, 10));
      visor.setBaseVideojuego(aux);
      visor.asignacionContenidoElementGraficos();
      contenedorVisor.add(visor);
      jVisorVideojuego.add(contenedorVisor);
    }
    jVisorVideojuego.revalidate();
    jVisorVideojuego.repaint();
  }

  @Override
  public void setControlador(Controlador c) {
    this.controlador = c;
  }

  @Override
  public void arranca() {
    pack();
    setLocationRelativeTo(null);
    setVisible(true);
  }

  @Override
  public void haceAlgo(String s) {
    //aaa
  }

  public List<String> obtenerGenerosSelected() {
    List<String> returnListGeneros = new ArrayList<>();
    
    for (Checkbox aux : listaGenerosSelected) {
      if (aux.getState() == true) {
        returnListGeneros.add(aux.getLabel());
      }
    } 
    
    return returnListGeneros;
  }

  public List<String> obtenerPlataformasSelected() {
    List<String> returnListPlataformas = new ArrayList<>();
    for (Checkbox aux : listaPlataformasSelected) {
      if (aux.getState() == true) {
        returnListPlataformas.add(aux.getLabel());
      }
    }
    
    return returnListPlataformas;
  }

  public List<String> obtenerModosJuegoSelected() {
    List<String> returnListModosJuego = new ArrayList<>();
    for (Checkbox aux : listaModosJuegoSelected) {
      if (aux.getState() == true) {
        returnListModosJuego.add(aux.getLabel());
      }
    }
    
    return returnListModosJuego;
  }


  public List<Integer> obtenerPEGISelected() {
    List<Integer> returnListPEGI = new ArrayList<>();
    for (Checkbox aux : listaPEGISelected) {
      if (aux.getState() == true) {
        returnListPEGI.add(Integer.valueOf(aux.getLabel()));
      }
    }
    
    return returnListPEGI;
  }
 //-------------------------------------------------------------------------------------------------------------->
  private void cargarOpcionesGenero () {
    panelOpcionesGenero.removeAll();
    List<String> listaGeneros = this.controlador.cargarNombresGeneros();
    
    for (String aux : listaGeneros) {
      java.awt.Checkbox genCheckBox = new Checkbox(aux, false);
      listaGenerosSelected.add(genCheckBox);
      panelOpcionesGenero.add(genCheckBox);
    }
  }
  
  private void cargarOpcionesPlataforma () {
    panelOpcionesPlataforma.removeAll();
    List<String> listaPlataformas = controlador.cargarNombresPlataformas();
    
    for (String aux : listaPlataformas) {
      java.awt.Checkbox genCheckBox = new Checkbox(aux, false);
      listaPlataformasSelected.add(genCheckBox);
      panelOpcionesPlataforma.add(genCheckBox);
    }
  }
  
  private void cargarOpcionesModosJuego () {
    panelOpcionesModoJuego.removeAll();
    List<String> listaModosJuego = controlador.cargarNombresModoJuego();
    
    for (String aux : listaModosJuego) {
      java.awt.Checkbox genCheckBox = new Checkbox(aux, false);
      listaModosJuegoSelected.add(genCheckBox);
      panelOpcionesModoJuego.add(genCheckBox);
    }
  }
  
  private void cargarOpcionesPEGI () {
    panelOpcionesPEGI.removeAll();
    List<String> listaPEGI = new ArrayList<>();
    
    for (Integer aux : controlador.cargarPEGIs()) {
      listaPEGI.add(Integer.toString(aux));
    }
    
    for (String aux : listaPEGI) {
      java.awt.Checkbox genCheckBox = new Checkbox(aux, false);
      listaPEGISelected.add(genCheckBox);
      panelOpcionesPEGI.add(genCheckBox);
    }
  }
}
