/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accdat.papergames.Vista;

import accdat.papergames.Controlador.Controlador;
import accdat.papergames.Controlador.ControladorCreacion;
import accdat.papergames.Modelo.Persistencia.ModoJuego;
import accdat.papergames.Modelo.Persistencia.Plataforma;
import accdat.papergames.Modelo.Persistencia.Videojuego;
import java.awt.Button;
import java.awt.Checkbox;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Label;
import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.Popup;
import javax.swing.PopupFactory;

/**
 *
 * @author rezzt
 */
public class VentanaCreateVideojuego extends javax.swing.JFrame implements InterfazVista {
 //------------------------------------------------------------------------------------------------------------------------------------->
  private ControladorCreacion controlador;
  private Controlador controladorBase;
  private VentanaPrincipal ventanaPadre;
  private Videojuego videojuegoSelected;
  
  private String titulo;
  private String descripcion;
  private String generoSelected;
  private int anioSalida;
  private int pegiSelected;
  private Collection<Plataforma> listaPlataformasSelected = new ArrayList<>();
  private Collection<ModoJuego> listaModosJuegoSelected = new ArrayList<>();
  
  private List<Checkbox> listaPlataformasCheckbox = new ArrayList<>();
  private List<Checkbox> listaModosJuegoCheckbox = new ArrayList<>();
  
  private List<String> listaPlataformasCBoxSelected = new ArrayList<>();
  private List<String> listaModosJuegoCBoxSelected = new ArrayList<>();
  
  
  
 //------------------------------------------------------------------------------------------------------------------------------------->
  /**
   * Creates new form VentanaCreateVideojuego
   */
  public VentanaCreateVideojuego() {
    initComponents();
    
    txtDescripcion.setLineWrap(true);
    txtDescripcion.setWrapStyleWord(true);
    scrollDescripcion.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    scrollDescripcion.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    iniciarComponentes();
  }
  
  private void iniciarComponentes () {
    this.controladorBase = new Controlador(this);
    this.controlador = new ControladorCreacion(this);
    panelListaPlataforma.setLayout(new GridLayout(0,1));
    panelListaModosJuego.setLayout(new GridLayout(0,1));
    
    cargarComboBoxGenero();
    cargarComboBoxPEGI();
    cargarCheckboxesPlataformas();
    cargarCheckboxesModosJuego();
  }
  
 //------------------------------------------------------------------------------------------------------------------------------------->

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    lblTituloVentana = new javax.swing.JLabel();
    panelProp1 = new javax.swing.JPanel();
    lblTitulo = new javax.swing.JLabel();
    txtTitulo = new javax.swing.JTextField();
    lblAnioSalida = new javax.swing.JLabel();
    spinnerAnioSalida = new javax.swing.JSpinner();
    lblPEGI = new javax.swing.JLabel();
    cboxListaPegi = new javax.swing.JComboBox<>();
    lblGeneros = new javax.swing.JLabel();
    cboxListaGenero = new javax.swing.JComboBox<>();
    jPanel2 = new javax.swing.JPanel();
    lblPlataformas = new javax.swing.JLabel();
    lblModosJuego = new javax.swing.JLabel();
    panelListaPlataforma = new javax.swing.JPanel();
    panelListaModosJuego = new javax.swing.JPanel();
    panelProp3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    scrollDescripcion = new javax.swing.JScrollPane();
    txtDescripcion = new javax.swing.JTextArea();
    btnAceptar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

    lblTituloVentana.setFont(new java.awt.Font("Comfortaa", 1, 18)); // NOI18N
    lblTituloVentana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTituloVentana.setText("INSERCION | VIDEOJUEGO");

    panelProp1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

    lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblTitulo.setText("Titulo");

    lblAnioSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblAnioSalida.setText("Año de Salida");

    spinnerAnioSalida.setModel(new javax.swing.SpinnerNumberModel(2020, 2000, 2029, 1));

    lblPEGI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblPEGI.setText("PEGI");

    lblGeneros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblGeneros.setText("Genero");

    javax.swing.GroupLayout panelProp1Layout = new javax.swing.GroupLayout(panelProp1);
    panelProp1.setLayout(panelProp1Layout);
    panelProp1Layout.setHorizontalGroup(
      panelProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtTitulo)
          .addComponent(lblAnioSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(spinnerAnioSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
          .addComponent(lblPEGI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cboxListaPegi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(lblGeneros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(cboxListaGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    panelProp1Layout.setVerticalGroup(
      panelProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(spinnerAnioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblPEGI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cboxListaPegi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cboxListaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

    lblPlataformas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblPlataformas.setText("Plataformas");

    lblModosJuego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblModosJuego.setText("Modos de Juego");

    javax.swing.GroupLayout panelListaPlataformaLayout = new javax.swing.GroupLayout(panelListaPlataforma);
    panelListaPlataforma.setLayout(panelListaPlataformaLayout);
    panelListaPlataformaLayout.setHorizontalGroup(
      panelListaPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelListaPlataformaLayout.setVerticalGroup(
      panelListaPlataformaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout panelListaModosJuegoLayout = new javax.swing.GroupLayout(panelListaModosJuego);
    panelListaModosJuego.setLayout(panelListaModosJuegoLayout);
    panelListaModosJuegoLayout.setHorizontalGroup(
      panelListaModosJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    panelListaModosJuegoLayout.setVerticalGroup(
      panelListaModosJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(lblPlataformas, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
          .addComponent(panelListaPlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblModosJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
          .addComponent(panelListaModosJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(lblModosJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblPlataformas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panelListaPlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelListaModosJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    panelProp3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Descripcion");

    txtDescripcion.setColumns(20);
    txtDescripcion.setRows(5);
    scrollDescripcion.setViewportView(txtDescripcion);

    javax.swing.GroupLayout panelProp3Layout = new javax.swing.GroupLayout(panelProp3);
    panelProp3.setLayout(panelProp3Layout);
    panelProp3Layout.setHorizontalGroup(
      panelProp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProp3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelProp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(scrollDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    panelProp3Layout.setVerticalGroup(
      panelProp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelProp3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(scrollDescripcion)
        .addContainerGap())
    );

    btnAceptar.setText("Aceptar");
    btnAceptar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAceptarActionPerformed(evt);
      }
    });

    btnCancelar.setText("Cancelar");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(panelProp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelProp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(lblTituloVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblTituloVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelProp1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(panelProp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 0, 0))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

 //------------------------------------------------------------------------------------------------------------------------------------->
  private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    recogerDatosCampos();
    crearVideojuego();
    this.ventanaPadre.agregarVisores(this.controlador.cargarVideojuegos());
    this.ventanaPadre.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_btnAceptarActionPerformed

  private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.ventanaPadre.agregarVisores(this.controlador.cargarVideojuegos());
    this.ventanaPadre.setVisible(true);
    this.dispose();
  }//GEN-LAST:event_btnCancelarActionPerformed

  
 //------------------------------------------------------------------------------------------------------------------------------------->
  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAceptar;
  private javax.swing.JButton btnCancelar;
  private javax.swing.JComboBox<String> cboxListaGenero;
  private javax.swing.JComboBox<String> cboxListaPegi;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel lblAnioSalida;
  private javax.swing.JLabel lblGeneros;
  private javax.swing.JLabel lblModosJuego;
  private javax.swing.JLabel lblPEGI;
  private javax.swing.JLabel lblPlataformas;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JLabel lblTituloVentana;
  private javax.swing.JPanel panelListaModosJuego;
  private javax.swing.JPanel panelListaPlataforma;
  private javax.swing.JPanel panelProp1;
  private javax.swing.JPanel panelProp3;
  private javax.swing.JScrollPane scrollDescripcion;
  private javax.swing.JSpinner spinnerAnioSalida;
  private javax.swing.JTextArea txtDescripcion;
  private javax.swing.JTextField txtTitulo;
  // End of variables declaration//GEN-END:variables
 //-------------------------------------------------------------------------------------------------------------------------------------> 
  private void recogerDatosCampos () {
    guardarPlataformasSeleccionadas();
    guardarModosJuegoSeleccionados();
    
    this.titulo = txtTitulo.getText();
    this.descripcion = txtDescripcion.getText();
    this.generoSelected = (String) cboxListaGenero.getSelectedItem();
    this.anioSalida = (int) spinnerAnioSalida.getValue();
    this.pegiSelected = Integer.parseInt(cboxListaPegi.getSelectedItem().toString());
    
    insertarPlataformas();
    insertarModosJuego();
  }
  
  private void crearVideojuego () {
    if (!titulo.isEmpty() && !descripcion.isEmpty() && !generoSelected.isEmpty() && !listaPlataformasSelected.isEmpty() && !listaModosJuegoSelected.isEmpty()) {
      this.controlador.crearNuevoVideojuego(titulo, descripcion,(short) anioSalida,(short) pegiSelected, generoSelected, listaPlataformasSelected, listaModosJuegoSelected);
    } else {
      generarPopup();
    }
  }
  
 //------------------------------------------------------------------------------------------------------------------------------------->
  private void generarPopup () {
    java.awt.Frame framePopup = new Frame("ERROR INSERCION VIDEOJUEGO");
      framePopup.setSize(400, 300);
      framePopup.setLayout(new GridLayout(0, 1));
      framePopup.setVisible(true);
      
      Label mensajePopup = new Label("ERROR EN LA MODIFICACION DEL VIDEOJUEGO");
      framePopup.add(mensajePopup);
      
      Button showPopupBtn = new Button("Aceptar");
      showPopupBtn.setBounds(150, 120, 100 ,30);
      framePopup.add(showPopupBtn);
      
      PopupFactory popupFactory = new PopupFactory();
      
      Label popupLabel = new Label("Datos introducidos de manera incorrecta");
        popupLabel.setBackground(Color.LIGHT_GRAY);
        popupLabel.setSize(150, 50);
        popupLabel.setAlignment(Label.CENTER);
      
      showPopupBtn.addActionListener(e -> {
        Point buttonLocation = showPopupBtn.getLocationOnScreen();
        Popup popup = popupFactory.getPopup(framePopup, popupLabel, buttonLocation.x, buttonLocation.y + 40);
        popup.hide();
        framePopup.dispose();
      });
      
      framePopup.addWindowListener(new WindowAdapter () {
        @Override
        public void windowClosing (WindowEvent e) {
          framePopup.dispose();
        }
      });
  }
  
 //-------------------------------------------------------------------------------------------------------------------------------------> 
  private void cargarComboBoxGenero () {
    cboxListaGenero.removeAll();
    List<String> listaNombresGeneros = this.controlador.cargarNombresGeneros();
     
    for (String aux : listaNombresGeneros) {
     cboxListaGenero.addItem(aux);
    }
  }
  private void cargarComboBoxPEGI () {
    cboxListaPegi.removeAll();
     
    for (Integer aux : this.controlador.cargarPEGIs()) {
      cboxListaPegi.addItem(Integer.toString(aux));
    }
  }
   
  private void cargarCheckboxesPlataformas () {
    panelListaPlataforma.removeAll();
    List<String> listaNombresPlataformas = this.controlador.cargarNombresPlataformas();
     
    for (String aux : listaNombresPlataformas) {
      Checkbox genCheckBox = new Checkbox(aux, false);
      listaPlataformasCheckbox.add(genCheckBox);
      panelListaPlataforma.add(genCheckBox);
    }
  }
  private void cargarCheckboxesModosJuego () {
    panelListaModosJuego.removeAll();
    List<String> listaNombresModosJuego = this.controlador.cargarNombresModoJuego();
     
    for (String aux : listaNombresModosJuego) {
      Checkbox genCheckBox = new Checkbox(aux, false);
      listaModosJuegoCheckbox.add(genCheckBox);
      panelListaModosJuego.add(genCheckBox);
    }
  }
   
 //------------------------------------------------------------------------------------------------------------------------------------->
   private void guardarPlataformasSeleccionadas () {
     for (Checkbox aux : listaPlataformasCheckbox) {
       if (aux.getState() == true) {
         listaPlataformasCBoxSelected.add(aux.getLabel());
       }
     }
   }
   private void guardarModosJuegoSeleccionados () {
     for (Checkbox aux : listaModosJuegoCheckbox) {
       if (aux.getState() == true) {
         listaModosJuegoCBoxSelected.add(aux.getLabel());
       }
     }
   }
   
 //------------------------------------------------------------------------------------------------------------------------------------->
  private void insertarPlataformas () {
    for (String aux : listaPlataformasCBoxSelected) {
      listaPlataformasSelected.add(this.controlador.encontrarPlataforma(aux));
    }
  }
  
  private void insertarModosJuego () {
    for (String aux : listaModosJuegoCBoxSelected) {
      listaModosJuegoSelected.add(this.controlador.encontrarModoJuego(aux));
    }
  }
  
 //------------------------------------------------------------------------------------------------------------------------------------->
  public VentanaPrincipal getVentanaPadre() {
    return ventanaPadre;
  }

  public void setVentanaPadre(VentanaPrincipal ventanaPadre) {
    this.ventanaPadre = ventanaPadre;
  }
  
  
 //------------------------------------------------------------------------------------------------------------------------------------->
  @Override
  public void agregarVisores(List<Videojuego> inputListaVideojuegos) {
    // -> no hace nada
  }

  @Override
  public void setControlador(Controlador c) {
    this.controladorBase = c;
  }

  @Override
  public void arranca() {
    this.controladorBase = new Controlador(this);
    this.controlador = new ControladorCreacion(this);
    pack();
    setLocationRelativeTo(null);
    setVisible(true);
    
  }

  @Override
  public Videojuego getVideojuegoSelected() {
    return videojuegoSelected;
  }

  @Override
  public void haceAlgo(String s) {
    // -> no hace nada
  }
  
}
